// Generated by CoffeeScript 1.6.1
(function() {

  window.sysmon_load = function() {
    var endpoint, onopen, ws;
    endpoint = "ws://localhost:8080/sys-mon/echo";
    onopen = function() {
      console.log("on open");
      return $(".status").html("connected");
    };
    return ws = new WebsocketHelper(endpoint, onopen);
  };

}).call(this);
