// Generated by CoffeeScript 1.6.1
(function() {
  var _this = this;

  window.SysMon = (function() {

    function SysMon() {
      var _this = this;
      this.load = function() {
        return SysMon.prototype.load.apply(_this, arguments);
      };
      this.ws = void 0;
    }

    SysMon.prototype.load = function() {
      var onmessage, onopen, w1,
        _this = this;
      w1 = "ws://localhost:8080/sys-mon/events";
      onopen = function() {
        console.log("on open");
        $(".status").html("connected");
        $(".status").removeClass("label-warning");
        return $(".status").addClass("label-info");
      };
      onmessage = function(msg) {
        console.log("on message");
        return $(".activity").append(msg);
      };
      this.ws = new WebsocketHelper(w1, onopen, onmessage);
      this.ws.connect(w1);
      return this.ws;
    };

    SysMon.prototype.initRefresherView = function() {
      var updateRefresh,
        _this = this;
      updateRefresh = function(e) {
        var $header, rate, tmpTimerTask;
        rate = Number($(e.target).attr("rate"));
        tmpTimerTask = function() {
          var d, refreshMsg, t;
          d = new Date();
          t = d.toLocaleTimeString();
          console.log(t);
          refreshMsg = {
            msg: "update"
          };
          return _this.ws.send(refreshMsg);
        };
        if (window.timerTask) {
          window.clearInterval(window.timerTask);
        }
        $header = $(".header");
        if (rate === 0) {
          $header.html("Activity Stream [off]");
          return;
        }
        window.timerTask = tmpTimerTask;
        window.setInterval(window.timerTask, rate);
        return $header.html("Activity Stream [" + rate + " ms]");
      };
      return $(".refresh-rate").on("click", updateRefresh);
    };

    return SysMon;

  })();

}).call(this);
