// Generated by CoffeeScript 1.6.1
(function() {
  var _this = this;

  window.SysMon = (function() {

    function SysMon() {
      var _this = this;
      this.load = function() {
        return SysMon.prototype.load.apply(_this, arguments);
      };
      this.ws = void 0;
    }

    SysMon.prototype.load = function() {
      var onclose, onmessage, onopen, w1,
        _this = this;
      w1 = "ws://localhost:8080/sys-mon/events";
      onclose = function() {
        var disconnect;
        console.log("closed connection..");
        disconnect = "disconnected";
        $(".activity").append(disconnect);
        $(".status").html(disconnect);
        $(".status").removeClass("label-info");
        return $(".status").addClass("label-warning");
      };
      onopen = function() {
        console.log("on open");
        $(".status").html("connected");
        $(".status").removeClass("label-warning");
        return $(".status").addClass("label-info");
      };
      onmessage = function(msgs) {
        var data;
        console.log("on message");
        if (msgs && msgs.data) {
          data = JSON.parse(msgs.data);
          if (_.isArray(data) && _.isEmpty(data)) {
            return;
          }
          _.chain(data).reverse().map(function(msg) {
            var el, li;
            if (msg && msg.eventType && msg.sysEvent) {
              el = msg.eventType + " - " + msg.sysEvent;
            } else {
              el = msg;
            }
            li = $("<li/>").html(el);
            return $(".activity > ul").prepend(li);
          }).value();
          return $(".activity > ul").prepend($("<hr/>"));
        } else {
          return console.log(msgs);
        }
      };
      this.ws = new WebsocketHelper(w1, onopen, onmessage, onclose);
      this.ws.connect(w1);
      return this.ws;
    };

    SysMon.prototype.initRefresherView = function() {
      var clearEvents, updateRefresh,
        _this = this;
      updateRefresh = function(e) {
        var $msgs, rate, tmpTimerTask;
        rate = Number($(e.target).attr("rate"));
        tmpTimerTask = function() {
          var d, refreshMsg, t;
          d = new Date();
          t = d.toLocaleTimeString();
          console.log(t);
          refreshMsg = {
            msg: "update"
          };
          return _this.ws.send(refreshMsg);
        };
        if (window.timerTask) {
          window.clearInterval(window.timerTask);
        }
        $msgs = $(".activitiy-msg");
        if (rate === 0) {
          $msgs.html("Activity Stream [off]");
          return;
        }
        window.timerTask = tmpTimerTask;
        window.setInterval(window.timerTask, rate);
        return $msgs.html("Activity Stream [" + rate + " ms]");
      };
      clearEvents = function(e) {
        return $(".activity > ul").html("");
      };
      $(".refresh-rate").on("click", updateRefresh);
      return $(".event-clear").on("click", clearEvents);
    };

    return SysMon;

  })();

}).call(this);
